name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          # MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: mysql@123
          MYSQL_DATABASE: usersdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Configure MySQL permissions
        run: mysql -h 127.0.0.1 --port 3306 -u root -pmysql@123 -e "ALTER USER 'root'@'%' IDENTIFIED BY 'mysql@123'; GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'; FLUSH PRIVILEGES;"
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: install cliente mysql
        run: sudo apt install mysql-client
      - name: create tables
        run:  mysql -h 127.0.0.1 --port 3306 -u root -pmysql@123 usersdb < estrutura.sql
      - name: Run tests
        env: 
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: mysql@123
            MYSQL_DATABASE: usersdb
        run: npm test